### ISSUE TITLE
`bokeh` 3.0.0 bug with `FuncTickFormatter` class

### ISSUE THREAD

**Issue by hover2pi** [hover2pi/hotsoss#6]
In `plotting.py` the import of `FuncTickFormatter` class breaks with `bokeh` v3.0.0 so it needs to be pinned to v2.4.2 until this is fixed. Here's a hot fix : https://stackoverflow.com/questions/42376878/python-bokeh-functickformatter

`bokeh` currently pinned to v1.2.2.

**Comment by rcooper295** [comment]
Just encountered this issue trying to import functions from hotsoss in an environment using python 3.12. I stepped down from 3.5.0 to 2.4.2 but ran into different problems importing bpm_utils (cannot import name 'TabPanel' from 'bokeh.models') so it seems like there might be a conflict here?

**Comment by hover2pi** [comment]
Yup, I fixed this but need to make a new release and upload to PyPI. Thanks!

**Comment by rcooper295** [comment]
Ah ok thanks, in the meantime I can just install from here

**Comment by hover2pi** [comment]
Fixed.
